[2024-08-07T11:13:18.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T11:13:18.614+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_2024-08-07.validate_the_api manual__2024-08-07T11:13:14.069976+00:00 [queued]>
[2024-08-07T11:13:18.618+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_2024-08-07.validate_the_api manual__2024-08-07T11:13:14.069976+00:00 [queued]>
[2024-08-07T11:13:18.619+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T11:13:18.666+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_api> on 2024-08-07 11:13:14.069976+00:00
[2024-08-07T11:13:18.669+0000] {standard_task_runner.py:63} INFO - Started process 5424 to run task
[2024-08-07T11:13:18.671+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_2024-08-07', 'validate_the_api', 'manual__2024-08-07T11:13:14.069976+00:00', '--job-id', '952', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpc7c9z8xc']
[2024-08-07T11:13:18.672+0000] {standard_task_runner.py:91} INFO - Job 952: Subtask validate_the_api
[2024-08-07T11:13:18.748+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_2024-08-07.validate_the_api manual__2024-08-07T11:13:14.069976+00:00 [running]> on host 8cffaad11d99
[2024-08-07T11:13:18.831+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_2024-08-07' AIRFLOW_CTX_TASK_ID='validate_the_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T11:13:14.069976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T11:13:14.069976+00:00'
[2024-08-07T11:13:18.831+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T11:13:18.838+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T11:13:18.839+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/api_utils.py']
[2024-08-07T11:13:18.845+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T11:13:19.068+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T11:13:19.068+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T11:13:19.121+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_2024-08-07, task_id=validate_the_api, run_id=manual__2024-08-07T11:13:14.069976+00:00, execution_date=20240807T111314, start_date=20240807T111318, end_date=20240807T111319
[2024-08-07T11:13:19.165+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-07T11:13:19.185+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-07T11:13:19.208+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
