[2024-08-21T06:02:29.111+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:02:29.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_22024-08-21.fetch_the_api manual__2024-08-21T06:02:28.137997+00:00 [queued]>
[2024-08-21T06:02:29.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_22024-08-21.fetch_the_api manual__2024-08-21T06:02:28.137997+00:00 [queued]>
[2024-08-21T06:02:29.269+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:02:29.351+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): fetch_the_api> on 2024-08-21 06:02:28.137997+00:00
[2024-08-21T06:02:29.389+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=559) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:02:29.394+0000] {standard_task_runner.py:63} INFO - Started process 569 to run task
[2024-08-21T06:02:29.393+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_22024-08-21', 'fetch_the_api', 'manual__2024-08-21T06:02:28.137997+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpd_0vi68s']
[2024-08-21T06:02:29.398+0000] {standard_task_runner.py:91} INFO - Job 106: Subtask fetch_the_api
[2024-08-21T06:02:29.557+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_22024-08-21.fetch_the_api manual__2024-08-21T06:02:28.137997+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:02:29.834+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_22024-08-21' AIRFLOW_CTX_TASK_ID='fetch_the_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T06:02:28.137997+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T06:02:28.137997+00:00'
[2024-08-21T06:02:29.836+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:02:29.883+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:02:29.886+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/config.py']
[2024-08-21T06:02:29.936+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:02:30.143+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:02:30.147+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:02:30.273+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_22024-08-21, task_id=fetch_the_api, run_id=manual__2024-08-21T06:02:28.137997+00:00, execution_date=20240821T060228, start_date=20240821T060229, end_date=20240821T060230
[2024-08-21T06:02:30.390+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:02:30.472+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
