[2024-08-21T06:27:36.566+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T06:27:36.624+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_22024-08-21.log_the_data scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-21T06:27:36.641+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_22024-08-21.log_the_data scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-21T06:27:36.643+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T06:27:36.768+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): log_the_data> on 2024-08-08 00:00:00+00:00
[2024-08-21T06:27:36.809+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4442) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T06:27:36.818+0000] {standard_task_runner.py:63} INFO - Started process 4451 to run task
[2024-08-21T06:27:36.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_22024-08-21', 'log_the_data', 'scheduled__2024-08-08T00:00:00+00:00', '--job-id', '738', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpb1tafjgf']
[2024-08-21T06:27:36.867+0000] {standard_task_runner.py:91} INFO - Job 738: Subtask log_the_data
[2024-08-21T06:27:37.185+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_22024-08-21.log_the_data scheduled__2024-08-08T00:00:00+00:00 [running]> on host 7e1333882d71
[2024-08-21T06:27:37.433+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_22024-08-21' AIRFLOW_CTX_TASK_ID='log_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-08T00:00:00+00:00'
[2024-08-21T06:27:37.436+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T06:27:37.482+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T06:27:37.487+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/logging_config.py']
[2024-08-21T06:27:37.510+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T06:27:37.903+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-21T06:27:37.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T06:27:38.017+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_22024-08-21, task_id=log_the_data, run_id=scheduled__2024-08-08T00:00:00+00:00, execution_date=20240808T000000, start_date=20240821T062736, end_date=20240821T062738
[2024-08-21T06:27:38.050+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T06:27:38.142+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T06:27:38.144+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
