[2024-08-07T11:11:22.176+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T11:11:22.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_2024-08-07.final_etl_processing scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-08-07T11:11:22.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_2024-08-07.final_etl_processing scheduled__2024-07-13T00:00:00+00:00 [queued]>
[2024-08-07T11:11:22.201+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T11:11:22.257+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): final_etl_processing> on 2024-07-13 00:00:00+00:00
[2024-08-07T11:11:22.261+0000] {standard_task_runner.py:63} INFO - Started process 4632 to run task
[2024-08-07T11:11:22.264+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_2024-08-07', 'final_etl_processing', 'scheduled__2024-07-13T00:00:00+00:00', '--job-id', '844', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpcrlhqmoc']
[2024-08-07T11:11:22.265+0000] {standard_task_runner.py:91} INFO - Job 844: Subtask final_etl_processing
[2024-08-07T11:11:22.344+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_2024-08-07.final_etl_processing scheduled__2024-07-13T00:00:00+00:00 [running]> on host 8cffaad11d99
[2024-08-07T11:11:22.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_2024-08-07' AIRFLOW_CTX_TASK_ID='final_etl_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-13T00:00:00+00:00'
[2024-08-07T11:11:22.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T11:11:22.514+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T11:11:22.514+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "python3 /opt/***/data/etl_m12.py --connection postgresql+psycopg2://***:***@postgres/postgres --csv ''"]
[2024-08-07T11:11:22.521+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T11:11:23.243+0000] {subprocess.py:93} INFO - /opt/***/data/etl_m12.py:23: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
[2024-08-07T11:11:23.243+0000] {subprocess.py:93} INFO -   Base = declarative_base()
[2024-08-07T11:11:23.289+0000] {subprocess.py:93} INFO - ERROR:root:Decryption error: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
[2024-08-07T11:11:24.295+0000] {subprocess.py:93} INFO - INFO:__main__:DataFrame columns: Index(['error', 'token', 'error_details'], dtype='object')
[2024-08-07T11:11:24.756+0000] {subprocess.py:93} INFO - INFO:__main__:DataFrame head:
[2024-08-07T11:11:24.757+0000] {subprocess.py:93} INFO -                                                error  ...                                      error_details
[2024-08-07T11:11:24.757+0000] {subprocess.py:93} INFO - 0  'departmentCode' is null or None in decrypted ...  ...  {'atmpt': '0', 'dataDate': '2023-03-31 00:00:0...
[2024-08-07T11:11:24.757+0000] {subprocess.py:93} INFO - 1   'frequencyId' is null or None in decrypted data.  ...  {'atmpt': '0', 'dataDate': '2023-03-31 00:00:0...
[2024-08-07T11:11:24.757+0000] {subprocess.py:93} INFO - 2  'instanceCode' is null or None in decrypted data.  ...  {'atmpt': '0', 'dataDate': '2023-03-31 00:00:0...
[2024-08-07T11:11:24.757+0000] {subprocess.py:93} INFO - 3    'level2Code' is null or None in decrypted data.  ...  {'atmpt': '0', 'dataDate': '2023-03-31 00:00:0...
[2024-08-07T11:11:24.758+0000] {subprocess.py:93} INFO - 4   'projectCode' is null or None in decrypted data.  ...  {'atmpt': '0', 'dataDate': '2023-03-31 00:00:0...
[2024-08-07T11:11:24.758+0000] {subprocess.py:93} INFO - 
[2024-08-07T11:11:24.758+0000] {subprocess.py:93} INFO - [5 rows x 3 columns]
[2024-08-07T11:11:25.214+0000] {subprocess.py:93} INFO - ERROR:__main__:Error creating tables: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_class_relname_nsp_index"
[2024-08-07T11:11:25.215+0000] {subprocess.py:93} INFO - DETAIL:  Key (relname, relnamespace)=(ETL_id_seq, 2200) already exists.
[2024-08-07T11:11:25.215+0000] {subprocess.py:93} INFO - 
[2024-08-07T11:11:25.216+0000] {subprocess.py:93} INFO - [SQL:
[2024-08-07T11:11:25.216+0000] {subprocess.py:93} INFO - CREATE TABLE "ETL" (
[2024-08-07T11:11:25.216+0000] {subprocess.py:93} INFO - 	id SERIAL NOT NULL,
[2024-08-07T11:11:25.217+0000] {subprocess.py:93} INFO - 	error_type VARCHAR,
[2024-08-07T11:11:25.217+0000] {subprocess.py:93} INFO - 	token VARCHAR,
[2024-08-07T11:11:25.217+0000] {subprocess.py:93} INFO - 	error_details VARCHAR,
[2024-08-07T11:11:25.218+0000] {subprocess.py:93} INFO - 	created_date DATE,
[2024-08-07T11:11:25.218+0000] {subprocess.py:93} INFO - 	PRIMARY KEY (id)
[2024-08-07T11:11:25.218+0000] {subprocess.py:93} INFO - )
[2024-08-07T11:11:25.219+0000] {subprocess.py:93} INFO - 
[2024-08-07T11:11:25.219+0000] {subprocess.py:93} INFO - ]
[2024-08-07T11:11:25.220+0000] {subprocess.py:93} INFO - (Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-08-07T11:11:25.703+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-07T11:11:25.704+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T11:11:25.778+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_2024-08-07, task_id=final_etl_processing, run_id=scheduled__2024-07-13T00:00:00+00:00, execution_date=20240713T000000, start_date=20240807T111122, end_date=20240807T111125
[2024-08-07T11:11:25.930+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-07T11:11:25.940+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T11:11:26.144+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
